services:
  postgres:
    image: postgres:18
    container_name: movie_management_db
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: