spring:
  profiles:
    active: local
  application:
    name: movie-management-api

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: validate

    flyway:
      enabled: true
      locations: classpath:db/migration